### ISSUE TITLE
Redundant `box-sizing` property in location loader

### ISSUE THREAD

**Issue by alamenai** [vineethtrv/loader#8]
```CSS
.loader::after {
  content: '';  
  box-sizing: border-box; /**HERE**/
  width: 48px;
  height: 48px;
  left: 0;
  bottom: 0;
  position: absolute;
  border-radius: 50% 50% 0;
  border: 15px solid #FFF;
  transform: rotate(45deg) translate(0, 0);
  box-sizing: border-box; /**HERE**/
  animation: animMarker 0.4s ease-in-out infinite alternate;
}
```
